### ISSUE TITLE
Update information about DiffusionRet

### ISSUE THREAD

**Issue by jpthu17** [showlab/Awesome-Video-Diffusion#16]
Congrats on the impressive work.

Our [DiffusionRet](https://openaccess.thecvf.com/content/ICCV2023/papers/Jin_DiffusionRet_Generative_Text-Video_Retrieval_with_Diffusion_Model_ICCV_2023_paper.pdf) has been accepted by ICCV 2023.  The code is available at [Code](https://github.com/jpthu17/DiffusionRet).

Could you please update the information on our paper?

**Comment by zhangjiewu** [comment]
Hi @jpthu17, congrats on your work on DiffusionRet! Information updated.
