### ISSUE TITLE
Add ICCV 2023 paper

### ISSUE THREAD

**Issue by rese1f** [showlab/Awesome-Video-Diffusion#2]
Hi! Could you please include our work StableVideo at ICCV 2023? Thank you so much!

StableVideo: Text-driven Consistency-aware Diffusion Video Editing
Wenhao Chai, Xun Guo, Gaoang Wang, Yan Lu
ICCV 2023
https://arxiv.org/abs/2308.09592

**Comment by junhaozhang98** [comment]
Thanks for noting! Merged.

**Comment by rese1f** [comment]
so quick! thanks!
