### ISSUE TITLE
Hi! Would you like to build a dataset section?

### ISSUE THREAD

**Issue by Yaofang-Liu** [showlab/Awesome-Video-Diffusion#34]
FYI, we have open-sourced a text-2-video dataset named ECTV, you may take a look at:

Dataset: https://huggingface.co/datasets/RaphaelLiu/EvalCrafter_T2V_Dataset
Paper: https://arxiv.org/abs/2310.11440
GitHub: https://github.com/evalcrafter/EvalCrafter

Many thanks for your awesome list!!!

**Comment by zhangjiewu** [comment]
I just added the dataset link to EvalCrafter paper.

**Comment by Yaofang-Liu** [comment]
Thank you very much!
