### ISSUE TITLE
Update information about TI2V-Zero

### ISSUE THREAD

**Issue by nihaomiao** [showlab/Awesome-Video-Diffusion#58]
Hi, @zhangjiewu, thanks a lot for your impressive work!

Our TI2V-Zero has been accepted to CVPR 2024, and our code is also available at this [link](https://github.com/merlresearch/TI2V-Zero).  Could you update the information on our paper?

Thanks again for your time!

**Comment by junhaozhang98** [comment]
Feel free to open a PR for updates.

**Comment by nihaomiao** [comment]
Hi, @junhaozhang98, I have created a PR. Please feel free to let me know if you have any questions. If anything is good, feel free to merge and close this issue. Thanks again for your efforts!

**Comment by junhaozhang98** [comment]
Thanks!
