### ISSUE TITLE
New paper

### ISSUE THREAD

**Issue by Yaofang-Liu** [showlab/Awesome-Video-Diffusion#76]
Hi, please see if you could add this paper about a new kind of video diffusion model for video generation 
Title: Redefining Temporal Modeling in Video Diffusion: The Vectorized Timestep Approach
arXiv: https://arxiv.org/abs/2410.03160
GitHub: https://github.com/Yaofang-Liu/FVDM

Many thanks for your awesome list!

**Comment by weijiawu** [comment]
done, thank you for your attention.
