### ISSUE TITLE
MovieGen has a Mismatched URL

### ISSUE THREAD

**Issue by VikramxD** [showlab/Awesome-Video-Diffusion#89]
Points to Pyramidflow paper website 
https://pyramid-flow.github.io/

Since the project doesn't have a github repo (yet)
link should point to this https://ai.meta.com/research/publications/movie-gen-a-cast-of-media-foundation-models/

**Comment by zhangjiewu** [comment]
It has been updated already. Thanks!

**Comment by VikramxD** [comment]
gg
